spring:
#  redis:
#    pool:
#      min-idle: 0
#      max-idle: 8
#      max-active: 8
#    port: 6379
#    host: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/starbucks
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
